### ISSUE TITLE
error loading shared libraries

### ISSUE THREAD

**Issue by anonymous007** [hmartiro/redox#23]
I need some help, i get this error after I compile the "hello world" example with the given command: g++ hello.cpp -o hello -std=c++11 -lredox -lev -lhiredis . So the compilation works good, without errors, but the execution gives me this error: "error while loading shared libraries: libredox.so.0: cannot open shared object file: No such file or directory"

NOTE: Please try not to be mean when you explain to me the problem, I'm kind of a noob with those things. I am thinking that I didn't do the installation correctly.

**Comment by hmartiro** [comment]
Did you do `sudo make install` after `make`? It might not be in your system path.

Try `ldconfig -p | grep libredox` and see if is found. Alternatively, `ldd hello` on your executable to see if the link is made.

**Comment by nullEuro** [comment]
I got the same error and investigated this a little further. The issue seems to be that `/usr/lib64` (where redox gets installed on a 64 bit system) is not a standard library path on Ubuntu (actually libredox.so and its symlinks are the only files in this directory). I would suggest dropping the `LIB_SUFFIX` from the CMakeLists (or only set it if we are not building for the host architecture, e.g. building for 32 bit on a 64 bit system).

**Comment by rodolfoamarques** [comment]
I'm getting this same issue.
I tried both suggestions from @hmartiro and got no response on the first command and "libredox.so.0 => not found" for the second.
Is the solution by @nullEuro the workaround? Replacing lib64 by lib in the CMakeLists?

**Comment by nullEuro** [comment]
@rodolfoamarques Alternatively you can compile your program with
`LD_LIBRARY_PATH=/usr/lib64 gcc ...`

**Comment by flyvbee** [comment]
To avoid this issue, we can link the redox library statically. 

g++ hello.cpp  -std=c++11  -o hello -lredox_static -lev -lhiredis -pthread -I../include -L../build
